[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci --prefix client", "npm ci --prefix server"]

[phases.build]
cmds = ["npm run build --prefix client"]

[start]
cmd = "cd server && node server.js"
